using Constants;

namespace Constants
{
    public enum APIModule
    {
        Award,
        AwardFramework,
        AwardingBodyMapping,
        AwardType,
        AwardUserType,
        Basket,
        BasketItem,
        Broadcast,
        BroadcastType,
        BulkEmail,
        BulkEmailLink,
        BulkEmailRecipient,
        BulkEmailRecipientEvent,
        Category,
        CategoryType,
        ClassCourseDate,
        Communication,
        Company,
        CompanyCourseOverride,
        CompanyGroup,
        CompanyText,
        CompanyUserCourse,
        CompanyWorkingSession,
        ConfigCode,
        Course,
        CourseDate,
        CourseDateBooking,
        CourseDateSession,
        CourseFileMetadata,
        CourseTemplate,
        CreditNote,
        Currency,
        CustomFieldMetadata,
        CustomForm,
        CustomListItem,
        Dashboard,
        Discount,
        DiscountRule,
        DocumentPackage,
        DocumentTemplate,
        ELearningPackage,
        EmailMessage,
        EmailSubscription,
        EmailTemplate,
        EmailType,
        EnquiryQuoteItem,
        EthnicOrigin,
        Fee,
        FileMetadata,
        Gadget2,
        Industry,
        Invoice,
        InvoiceItem,
        InvoiceLog,
        LegacyReport,
        Login,
        ManagerBookableCourseDate,
        ManagerBookableCourseTemplate,
        ManagerCompany,
        ManagerCreditNote,
        ManagerEvaluationRequest,
        ManagerInvoice,
        ManagerPlaceholder,
        ManagerUser,
        ManagerUserAward,
        ManagerUserCourse,
        ManagerUserCourseDate,
        ManagerUserCourseDateAuthorisation,
        ManagerVoucherMapping,
        Meeting,
        MeetingAttendee,
        ModuleUnit,
        Nationality,
        Note,
        ObjectEventQueue,
        Opportunity,
        OpportunityHistoryItem,
        OpportunityItem,
        OpportunityMapping,
        Placeholder,
        PriceScheme,
        PriceSchemeMapping,
        Product,
        ProductMapping,
        Purchase,
        Report,
        RequestsLog,
        Resource,
        ResourceAvailability,
        ResourceAvailabilityException,
        ResourceRequirement,
        ResourceRequirementCourseDate,
        ResourceType,
        Role,
        SavedForm,
        SessionPlan,
        SessionPlanItem,
        ShoppingBasket3,
        ShoppingBasket3Item,
        SpecialNeed,
        Survey,
        SurveyAnswer,
        SurveyRecipient,
        SystemEventLog,
        Task,
        TaskMapping,
        TaskTemplate,
        TextTemplate,
        TimeZone,
        Token,
        TrainerConfirmation,
        TrainingPointsType,
        Transaction,
        TransactionInvoice,
        TransactionMethod,
        User,
        UserAward,
        UserCommunication,
        UserCompany,
        UserCourse,
        UserCourseDate,
        UserCourseDateClass,
        UserCourseDateDocuments,
        UserCourseDateELearning,
        UserCourseDateModule,
        UserCourseDateStatusReason,
        UserCourseDateWeb,
        UserNote,
        UserRole,
        UserType,
        UserUserType,
        Venue,
        ViabilityItem,
        Voucher,
        VoucherMapping,
        WebCourseDate,
        Webhook,
        WebhookInstance,
        WorkflowTemplate
    }
}

public static class APIModuleExtensions
{
    public static string ToModuleString(this APIModule module)
    {
        return module switch
        {
            APIModule.Award => "Award",
            APIModule.AwardFramework => "AwardFramework",
            APIModule.AwardingBodyMapping => "AwardingBodyMapping",
            APIModule.AwardType => "AwardType",
            APIModule.AwardUserType => "AwardUserType",
            APIModule.Basket => "Basket",
            APIModule.BasketItem => "BasketItem",
            APIModule.Broadcast => "Broadcast",
            APIModule.BroadcastType => "BroadcastType",
            APIModule.BulkEmail => "BulkEmail",
            APIModule.BulkEmailLink => "BulkEmailLink",
            APIModule.BulkEmailRecipient => "BulkEmailRecipient",
            APIModule.BulkEmailRecipientEvent => "BulkEmailRecipientEvent",
            APIModule.Category => "Category",
            APIModule.CategoryType => "CategoryType",
            APIModule.ClassCourseDate => "ClassCourseDate",
            APIModule.Communication => "Communication",
            APIModule.Company => "Company",
            APIModule.CompanyCourseOverride => "CompanyCourseOverride",
            APIModule.CompanyGroup => "CompanyGroup",
            APIModule.CompanyText => "CompanyText",
            APIModule.CompanyUserCourse => "CompanyUserCourse",
            APIModule.CompanyWorkingSession => "CompanyWorkingSession",
            APIModule.ConfigCode => "ConfigCode",
            APIModule.Course => "Course",
            APIModule.CourseDate => "CourseDate",
            APIModule.CourseDateBooking => "CourseDateBooking",
            APIModule.CourseDateSession => "CourseDateSession",
            APIModule.CourseFileMetadata => "CourseFileMetadata",
            APIModule.CourseTemplate => "CourseTemplate",
            APIModule.CreditNote => "CreditNote",
            APIModule.Currency => "Currency",
            APIModule.CustomFieldMetadata => "CustomFieldMetadata",
            APIModule.CustomForm => "CustomForm",
            APIModule.CustomListItem => "CustomListItem",
            APIModule.Dashboard => "Dashboard",
            APIModule.Discount => "Discount",
            APIModule.DiscountRule => "DiscountRule",
            APIModule.DocumentPackage => "DocumentPackage",
            APIModule.DocumentTemplate => "DocumentTemplate",
            APIModule.ELearningPackage => "ELearningPackage",
            APIModule.EmailMessage => "EmailMessage",
            APIModule.EmailSubscription => "EmailSubscription",
            APIModule.EmailTemplate => "EmailTemplate",
            APIModule.EmailType => "EmailType",
            APIModule.EnquiryQuoteItem => "EnquiryQuoteItem",
            APIModule.EthnicOrigin => "EthnicOrigin",
            APIModule.Fee => "Fee",
            APIModule.FileMetadata => "FileMetadata",
            APIModule.Gadget2 => "Gadget2",
            APIModule.Industry => "Industry",
            APIModule.Invoice => "Invoice",
            APIModule.InvoiceItem => "InvoiceItem",
            APIModule.InvoiceLog => "InvoiceLog",
            APIModule.LegacyReport => "LegacyReport",
            APIModule.Login => "Login",
            APIModule.ManagerBookableCourseDate => "ManagerBookableCourseDate",
            APIModule.ManagerBookableCourseTemplate => "ManagerBookableCourseTemplate",
            APIModule.ManagerCompany => "ManagerCompany",
            APIModule.ManagerCreditNote => "ManagerCreditNote",
            APIModule.ManagerEvaluationRequest => "ManagerEvaluationRequest",
            APIModule.ManagerInvoice => "ManagerInvoice",
            APIModule.ManagerPlaceholder => "ManagerPlaceholder",
            APIModule.ManagerUser => "ManagerUser",
            APIModule.ManagerUserAward => "ManagerUserAward",
            APIModule.ManagerUserCourse => "ManagerUserCourse",
            APIModule.ManagerUserCourseDate => "ManagerUserCourseDate",
            APIModule.ManagerUserCourseDateAuthorisation => "ManagerUserCourseDateAuthorisation",
            APIModule.ManagerVoucherMapping => "ManagerVoucherMapping",
            APIModule.Meeting => "Meeting",
            APIModule.MeetingAttendee => "MeetingAttendee",
            APIModule.ModuleUnit => "ModuleUnit",
            APIModule.Nationality => "Nationality",
            APIModule.Note => "Note",
            APIModule.ObjectEventQueue => "ObjectEventQueue",
            APIModule.Opportunity => "Opportunity",
            APIModule.OpportunityHistoryItem => "OpportunityHistoryItem",
            APIModule.OpportunityItem => "OpportunityItem",
            APIModule.OpportunityMapping => "OpportunityMapping",
            APIModule.Placeholder => "Placeholder",
            APIModule.PriceScheme => "PriceScheme",
            APIModule.PriceSchemeMapping => "PriceSchemeMapping",
            APIModule.Product => "Product",
            APIModule.ProductMapping => "ProductMapping",
            APIModule.Purchase => "Purchase",
            APIModule.Report => "Report",
            APIModule.RequestsLog => "RequestsLog",
            APIModule.Resource => "Resource",
            APIModule.ResourceAvailability => "ResourceAvailability",
            APIModule.ResourceAvailabilityException => "ResourceAvailabilityException",
            APIModule.ResourceRequirement => "ResourceRequirement",
            APIModule.ResourceRequirementCourseDate => "ResourceRequirementCourseDate",
            APIModule.ResourceType => "ResourceType",
            APIModule.Role => "Role",
            APIModule.SavedForm => "SavedForm",
            APIModule.SessionPlan => "SessionPlan",
            APIModule.SessionPlanItem => "SessionPlanItem",
            APIModule.ShoppingBasket3 => "ShoppingBasket3",
            APIModule.ShoppingBasket3Item => "ShoppingBasket3Item",
            APIModule.SpecialNeed => "SpecialNeed",
            APIModule.Survey => "Survey",
            APIModule.SurveyAnswer => "SurveyAnswer",
            APIModule.SurveyRecipient => "SurveyRecipient",
            APIModule.SystemEventLog => "SystemEventLog",
            APIModule.Task => "Task",
            APIModule.TaskMapping => "TaskMapping",
            APIModule.TaskTemplate => "TaskTemplate",
            APIModule.TextTemplate => "TextTemplate",
            APIModule.TimeZone => "TimeZone",
            APIModule.Token => "Token",
            APIModule.TrainerConfirmation => "TrainerConfirmation",
            APIModule.TrainingPointsType => "TrainingPointsType",
            APIModule.Transaction => "Transaction",
            APIModule.TransactionInvoice => "TransactionInvoice",
            APIModule.TransactionMethod => "TransactionMethod",
            APIModule.User => "User",
            APIModule.UserAward => "UserAward",
            APIModule.UserCommunication => "UserCommunication",
            APIModule.UserCompany => "UserCompany",
            APIModule.UserCourse => "UserCourse",
            APIModule.UserCourseDate => "UserCourseDate",
            APIModule.UserCourseDateClass => "UserCourseDateClass",
            APIModule.UserCourseDateDocuments => "UserCourseDateDocuments",
            APIModule.UserCourseDateELearning => "UserCourseDateELearning",
            APIModule.UserCourseDateModule => "UserCourseDateModule",
            APIModule.UserCourseDateStatusReason => "UserCourseDateStatusReason",
            APIModule.UserCourseDateWeb => "UserCourseDateWeb",
            APIModule.UserNote => "UserNote",
            APIModule.UserRole => "UserRole",
            APIModule.UserType => "UserType",
            APIModule.UserUserType => "UserUserType",
            APIModule.Venue => "Venue",
            APIModule.ViabilityItem => "ViabilityItem",
            APIModule.Voucher => "Voucher",
            APIModule.VoucherMapping => "VoucherMapping",
            APIModule.WebCourseDate => "WebCourseDate",
            APIModule.Webhook => "Webhook",
            APIModule.WebhookInstance => "WebhookInstance",
            APIModule.WorkflowTemplate => "WorkflowTemplate",
            _ => throw new ArgumentOutOfRangeException(nameof(module), module, null)
        };
    }
}